package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	dbgen "github.com/tr1xdev/aerogram-messenger/internal/database/sqlc/gen"
	"github.com/tr1xdev/aerogram-messenger/internal/graph"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	authv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/auth/v1"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.AuthPayload, error) {
	req := &authv1.SignUpRequest{
		Email:     input.Email,
		FirstName: input.FirstName,
		Password:  input.Password,
		LastName:  input.LastName,
		Username:  input.Username,
	}

	resp, err := r.AuthClient.SignUp(ctx, req)
	if err != nil {
		return nil, helpers.MapGRPCError(err)
	}

	return &model.AuthPayload{
		UserID: &resp.UserId,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Login(ctx, &authv1.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, helpers.MapGRPCError(err)
	}

	return &model.AuthPayload{
		UserID: &resp.UserId,
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input model.VerifyEmailInput) (*model.VerifyEmailPayload, error) {
	resp, err := r.AuthClient.VerifyEmail(ctx, &authv1.VerifyEmailRequest{
		UserId: input.UserID,
		Code:   input.Code,
	})
	if err != nil {
		return nil, helpers.MapGRPCError(err)
	}

	return &model.VerifyEmailPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.VerifyEmailPayload, error) {
	resp, err := r.AuthClient.RefreshToken(ctx, &authv1.RefreshTokenRequest{
		RefreshToken: token,
	})
	if err != nil {
		return nil, helpers.MapGRPCError(err)
	}

	return &model.VerifyEmailPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// TerminateAllOtherSessions is the resolver for the terminateAllOtherSessions field.
func (r *mutationResolver) TerminateAllOtherSessions(ctx context.Context) (bool, error) {
	userIDStr := middleware.GetUserID(ctx)
	sessionIDStr := middleware.GetSessionID(ctx)
	if userIDStr == "" || sessionIDStr == "" {
		return false, fmt.Errorf("unauthorized")
	}

	uid, errU := uuid.Parse(userIDStr)
	sid, errS := uuid.Parse(sessionIDStr)
	if errU != nil || errS != nil {
		return false, fmt.Errorf("invalid session or user id")
	}

	sessions, err := r.Store.GetSessionsByUserID(ctx, uid)
	if err != nil {
		return false, err
	}

	for _, s := range sessions {
		if s.ID != sid {
			r.Store.DeactivateSession(ctx, s.ID)
			r.RedisClient.Publish(ctx, "kill:session:"+s.ID.String(), "terminated")
		}
	}

	return true, nil
}

// TerminateSession is the resolver for the terminateSession field.
func (r *mutationResolver) TerminateSession(ctx context.Context, id string) (bool, error) {
	userIDStr := middleware.GetUserID(ctx)
	if userIDStr == "" {
		return false, fmt.Errorf("unauthorized")
	}

	sid, _ := uuid.Parse(id)

	err := r.Store.DeactivateSession(ctx, sid)
	if err != nil {
		return false, err
	}

	r.RedisClient.Publish(ctx, "kill:session:"+id, "terminated")
	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	sessionIDStr := middleware.GetSessionID(ctx)
	if sessionIDStr == "" {
		return false, fmt.Errorf("no active session found")
	}

	sid, _ := uuid.Parse(sessionIDStr)
	if err := r.Store.DeactivateSession(ctx, sid); err != nil {
		return false, err
	}

	r.RedisClient.Publish(ctx, "kill:session:"+sessionIDStr, "terminated")
	return true, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, userID string) ([]*dbgen.Session, error) {
	authID := middleware.GetUserID(ctx)
	if authID != userID {
		return nil, fmt.Errorf("permission denied")
	}

	uid, _ := uuid.Parse(userID)
	dbSessions, err := r.Store.GetSessionsByUserID(ctx, uid)
	if err != nil {
		return nil, err
	}

	res := make([]*dbgen.Session, len(dbSessions))
	for i := range dbSessions {
		res[i] = &dbSessions[i]
	}
	return res, nil
}

// ID is the resolver for the id field.
func (r *sessionResolver) ID(ctx context.Context, obj *dbgen.Session) (string, error) {
	return obj.ID.String(), nil
}

// Device is the resolver for the device field.
func (r *sessionResolver) Device(ctx context.Context, obj *dbgen.Session) (*string, error) {
	if obj.Device == "" {
		res := "Unknown Device"
		return &res, nil
	}
	name := r.UaService.Parse(obj.Device)
	return &name, nil
}

// Location is the resolver for the location field.
func (r *sessionResolver) Location(ctx context.Context, obj *dbgen.Session) (*string, error) {
	if obj.IpAddress == "" || obj.IpAddress == "127.0.0.1" || obj.IpAddress == "::1" {
		res := "Local Network"
		return &res, nil
	}
	res := r.GeoService.Lookup(obj.IpAddress)
	return &res, nil
}

// IsCurrent is the resolver for the isCurrent field.
func (r *sessionResolver) IsCurrent(ctx context.Context, obj *dbgen.Session) (bool, error) {
	return obj.ID.String() == middleware.GetSessionID(ctx), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *sessionResolver) CreatedAt(ctx context.Context, obj *dbgen.Session) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// Session returns graph.SessionResolver implementation.
func (r *Resolver) Session() graph.SessionResolver { return &sessionResolver{r} }

type sessionResolver struct{ *Resolver }
