package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"errors"
	"strings"
	"time"

	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	chatv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/chat/v1"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
)

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, typeArg model.ChatType, participantIds []string, slug *string, title *string) (model.CreateChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	enumKey := "CHAT_TYPE_" + strings.ToUpper(string(typeArg))
	req := &chatv1.CreateChatRequest{
		Type:           chatv1.ChatType(chatv1.ChatType_value[enumKey]),
		ParticipantIds: participantIds,
		CreatorId:      authID,
		Title:          title,
		Slug:           slug,
	}

	resp, err := r.ChatClient.CreateChat(ctx, req)
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return helpers.EnrichChat(ctx, r.Store, authID, resp.Chat)
}

// CreateDirectChat is the resolver for the createDirectChat field.
func (r *mutationResolver) CreateDirectChat(ctx context.Context, userID string) (model.CreateChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	resp, err := r.ChatClient.CreateChat(ctx, &chatv1.CreateChatRequest{
		Type:           chatv1.ChatType_CHAT_TYPE_PRIVATE,
		ParticipantIds: []string{authID, userID},
		CreatorId:      authID,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return helpers.EnrichChat(ctx, r.Store, authID, resp.Chat)
}

// PinChat is the resolver for the pinChat field.
func (r *mutationResolver) PinChat(ctx context.Context, id string, pinned bool) (model.PinChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	resp, err := r.ChatClient.PinChat(ctx, &chatv1.PinChatRequest{
		ChatId: id,
		UserId: authID,
		Pinned: pinned,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return &model.SuccessResult{Success: resp.GetSuccess()}, nil
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, id string, forEveryone *bool) (model.DeleteChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	everyone := false
	if forEveryone != nil {
		everyone = *forEveryone
	}

	resp, err := r.ChatClient.DeleteChat(ctx, &chatv1.DeleteChatRequest{
		ChatId:      id,
		UserId:      authID,
		ForEveryone: everyone,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return &model.SuccessResult{Success: resp.GetSuccess()}, nil
}

// SendTypingEvent is the resolver for the sendTypingEvent field.
func (r *mutationResolver) SendTypingEvent(ctx context.Context, chatID string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, nil
	}
	payload, _ := json.Marshal(map[string]string{"userId": authID, "status": "typing", "chatId": chatID})
	r.RedisClient.Publish(ctx, "presence:updates", payload)
	return true, nil
}

// MyChats is the resolver for the myChats field.
func (r *queryResolver) MyChats(ctx context.Context) (model.MyChatsResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	resp, err := r.ChatClient.GetMyChats(ctx, &chatv1.GetMyChatsRequest{UserId: authID})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	chats := make([]*model.Chat, 0, len(resp.Chats))
	for _, c := range resp.Chats {
		if enriched, err := helpers.EnrichChat(ctx, r.Store, authID, c); err == nil {
			chats = append(chats, enriched)
		}
	}

	return &model.ChatList{Chats: chats}, nil
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id *string, slug *string) (model.ChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	resp, err := r.ChatClient.GetChat(ctx, &chatv1.GetChatRequest{
		ChatId: id,
		Slug:   slug,
		UserId: authID,
	})
	if err != nil {
		return &model.NotFoundError{Message: "chat not found"}, nil
	}

	return helpers.EnrichChat(ctx, r.Store, authID, resp.Chat)
}

// ChatCreated is the resolver for the chatCreated field.
func (r *subscriptionResolver) ChatCreated(ctx context.Context, userID string) (<-chan *model.Chat, error) {
	chatChan := make(chan *model.Chat, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "user_chats:"+userID)

	go func() {
		defer pubsub.Close()
		defer close(chatChan)
		for msg := range pubsub.Channel() {
			var c model.Chat
			if err := json.Unmarshal([]byte(msg.Payload), &c); err == nil {
				chatChan <- &c
			}
		}
	}()
	return chatChan, nil
}

// ChatDeleted is the resolver for the chatDeleted field.
func (r *subscriptionResolver) ChatDeleted(ctx context.Context, userID string) (<-chan string, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" || authID != userID {
		return nil, errors.New("forbidden")
	}

	deleteChan := make(chan string, 5)
	pubsub := r.RedisClient.Subscribe(ctx, "user_chats_deleted:"+userID)

	go func() {
		defer pubsub.Close()
		defer close(deleteChan)

		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}
				select {
				case deleteChan <- msg.Payload:
				case <-time.After(time.Millisecond * 100):
					continue
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return deleteChan, nil
}
