package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"errors"
	"strings"

	"github.com/tr1xdev/aerogram-messenger/internal/graph"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	chatv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/chat/v1"
	presencev1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/presence/v1"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
)

// ID is the resolver for the id field.
func (r *chatResolver) ID(ctx context.Context, obj *model.Chat) (string, error) {
	return helpers.EncodeGlobalID("Chat", helpers.ToRawID(obj.ID)), nil
}

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, typeArg model.ChatType, participantIds []string, slug *string, title *string) (model.CreateChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	rawParticipantIds := make([]string, len(participantIds))
	for i, id := range participantIds {
		rawParticipantIds[i] = helpers.ToRawID(id)
	}

	enumKey := "CHAT_TYPE_" + strings.ToUpper(string(typeArg))
	req := &chatv1.CreateChatRequest{
		Type:           chatv1.ChatType(chatv1.ChatType_value[enumKey]),
		ParticipantIds: rawParticipantIds,
		CreatorId:      authID,
		Title:          title,
		Slug:           slug,
	}

	resp, err := r.ChatClient.CreateChat(ctx, req)
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return r.Enricher.EnrichChat(ctx, authID, resp.Chat)
}

// CreateDirectChat is the resolver for the createDirectChat field.
func (r *mutationResolver) CreateDirectChat(ctx context.Context, userID string) (model.CreateChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	rawUserID := helpers.ToRawID(userID)
	if authID == rawUserID {
		return &model.InternalError{Message: "you cannot create a chat with yourself"}, nil
	}

	resp, err := r.ChatClient.CreateChat(ctx, &chatv1.CreateChatRequest{
		Type:           chatv1.ChatType_CHAT_TYPE_PRIVATE,
		ParticipantIds: []string{authID, rawUserID},
		CreatorId:      authID,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return r.Enricher.EnrichChat(ctx, authID, resp.Chat)
}

// PinChat is the resolver for the pinChat field.
func (r *mutationResolver) PinChat(ctx context.Context, id string, pinned bool) (model.PinChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	resp, err := r.ChatClient.PinChat(ctx, &chatv1.PinChatRequest{
		ChatId: helpers.ToRawID(id),
		UserId: authID,
		Pinned: pinned,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return &model.SuccessResult{Success: resp.GetSuccess()}, nil
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, id string, forEveryone *bool) (model.DeleteChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	everyone := false
	if forEveryone != nil {
		everyone = *forEveryone
	}

	resp, err := r.ChatClient.DeleteChat(ctx, &chatv1.DeleteChatRequest{
		ChatId:      helpers.ToRawID(id),
		UserId:      authID,
		ForEveryone: everyone,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	return &model.SuccessResult{Success: resp.GetSuccess()}, nil
}

// SendTypingEvent is the resolver for the sendTypingEvent field.
func (r *mutationResolver) SendTypingEvent(ctx context.Context, chatID string, typing bool) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, nil
	}

	if err := r.PresenceSvc.PublishTyping(ctx, authID, helpers.ToRawID(chatID), typing); err != nil {
		return false, err
	}

	return true, nil
}

// MyChats is the resolver for the myChats field.
func (r *queryResolver) MyChats(ctx context.Context) (model.MyChatsResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	resp, err := r.ChatClient.GetMyChats(ctx, &chatv1.GetMyChatsRequest{UserId: authID})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	chats := make([]*model.Chat, 0, len(resp.Chats))
	for _, c := range resp.Chats {
		if enriched, err := r.Enricher.EnrichChat(ctx, authID, c); err == nil {
			chats = append(chats, enriched)
		}
	}

	return &model.ChatList{Chats: chats}, nil
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id *string, slug *string) (model.ChatResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "unauthorized"}, nil
	}

	var rawID *string
	if id != nil {
		val := helpers.ToRawID(*id)
		rawID = &val
	}

	resp, err := r.ChatClient.GetChat(ctx, &chatv1.GetChatRequest{
		ChatId: rawID,
		Slug:   slug,
		UserId: authID,
	})
	if err != nil {
		return &model.NotFoundError{Message: "chat not found"}, nil
	}

	return r.Enricher.EnrichChat(ctx, authID, resp.Chat)
}

// ChatCreated is the resolver for the chatCreated field.
func (r *subscriptionResolver) ChatCreated(ctx context.Context, userID string) (<-chan *model.Chat, error) {
	authID := middleware.GetUserID(ctx)
	rawUserID := helpers.ToRawID(userID)
	if authID == "" || authID != rawUserID {
		return nil, errors.New("forbidden")
	}

	chatChan := make(chan *model.Chat, 10)
	pubsub := r.RedisClient.Subscribe(ctx, "user_chats:"+rawUserID)

	go func() {
		defer pubsub.Close()
		defer close(chatChan)
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}

				var c model.Chat
				if err := json.Unmarshal([]byte(msg.Payload), &c); err != nil {
					continue
				}

				if c.ID == "" {
					continue
				}

				c.ID = helpers.EncodeGlobalID("Chat", helpers.ToRawID(c.ID))

				select {
				case chatChan <- &c:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return chatChan, nil
}

// ChatDeleted is the resolver for the chatDeleted field.
func (r *subscriptionResolver) ChatDeleted(ctx context.Context, userID string) (<-chan string, error) {
	authID := middleware.GetUserID(ctx)
	rawUserID := helpers.ToRawID(userID)
	if authID == "" || authID != rawUserID {
		return nil, errors.New("forbidden")
	}

	deleteChan := make(chan string, 10)
	pubsub := r.RedisClient.Subscribe(ctx, "user_chats_deleted:"+rawUserID)

	go func() {
		defer pubsub.Close()
		defer close(deleteChan)

		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}
				select {
				case deleteChan <- helpers.EncodeGlobalID("Chat", msg.Payload):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return deleteChan, nil
}

// UserTyping is the resolver for the userTyping field.
func (r *subscriptionResolver) UserTyping(ctx context.Context, chatID string) (<-chan *model.TypingPayload, error) {
	rawChatID := helpers.ToRawID(chatID)
	stream, err := r.PresenceClient.SubscribeTyping(ctx, &presencev1.SubscribeTypingRequest{ChatId: rawChatID})
	if err != nil {
		return nil, err
	}

	out := make(chan *model.TypingPayload, 10)

	go func() {
		defer close(out)
		for {
			resp, err := stream.Recv()
			if err != nil {
				return
			}

			var payload model.TypingPayload
			if err := json.Unmarshal([]byte(resp.Payload), &payload); err != nil {
				continue
			}

			payload.UserID = helpers.EncodeGlobalID("User", helpers.ToRawID(payload.UserID))

			select {
			case out <- &payload:
			case <-ctx.Done():
				return
			}
		}
	}()

	return out, nil
}

// Chat returns graph.ChatResolver implementation.
func (r *Resolver) Chat() graph.ChatResolver { return &chatResolver{r} }

type chatResolver struct{ *Resolver }
