package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	dbgen "github.com/tr1xdev/aerogram-messenger/internal/database/sqlc/gen"
	"github.com/tr1xdev/aerogram-messenger/internal/graph"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/loaders"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	messagesv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/messages/v1"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
)

// Sender is the resolver for the sender field.
func (r *messageResolver) Sender(ctx context.Context, obj *model.Message) (*dbgen.User, error) {
	if obj == nil || obj.Sender == nil || obj.Sender.ID == uuid.Nil {
		return &dbgen.User{
			ID:        uuid.Nil,
			FirstName: "Deleted",
			Username:  sql.NullString{String: "user", Valid: true},
		}, nil
	}

	user, err := loaders.LoadUser(ctx, obj.Sender.ID.String())
	if err != nil {
		return &dbgen.User{
			ID:        obj.Sender.ID,
			FirstName: "Unknown",
			Username:  sql.NullString{String: "unknown", Valid: true},
		}, nil
	}

	return user, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, chatID string, text string, isEncrypted bool, encryptionIv *string, replyToID *string) (model.SendMessageResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "Unauthorized"}, nil
	}

	resp, err := r.MessagesClient.SendMessage(ctx, &messagesv1.SendMessageRequest{
		ChatId:       chatID,
		SenderId:     authID,
		Text:         text,
		IsEncrypted:  isEncrypted,
		EncryptionIv: encryptionIv,
		ReplyToId:    replyToID,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	msg := helpers.MapMessageToModel(resp.Message)

	if replyToID != nil && *replyToID != "" {
		if replyMsg, err := loaders.LoadMessage(ctx, *replyToID); err == nil {
			msg.ReplyTo = replyMsg
		}
	}

	payload, _ := json.Marshal(msg)
	r.RedisClient.Publish(ctx, "chat:"+chatID, payload)

	return msg, nil
}

// UpdateMessage is the resolver for the updateMessage field.
func (r *mutationResolver) UpdateMessage(ctx context.Context, id string, text string, encryptionIv *string) (model.SendMessageResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "Unauthorized"}, nil
	}

	resp, err := r.MessagesClient.UpdateMessage(ctx, &messagesv1.UpdateMessageRequest{
		Id:           id,
		SenderId:     authID,
		Text:         text,
		EncryptionIv: encryptionIv,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	msg := helpers.MapMessageToModel(resp.Message)

	payload, _ := json.Marshal(msg)
	r.RedisClient.Publish(ctx, "chat:"+resp.Message.ChatId, payload)

	return msg, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, nil
	}

	_, err := r.MessagesClient.DeleteMessage(ctx, &messagesv1.DeleteMessageRequest{
		Id:       id,
		SenderId: authID,
	})
	return err == nil, nil
}

// MarkDialogAsRead is the resolver for the markDialogAsRead field.
func (r *mutationResolver) MarkDialogAsRead(ctx context.Context, chatID string, lastSequence int64) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, nil
	}

	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return false, err
	}

	msg, err := r.Store.GetMessageBySequence(ctx, dbgen.GetMessageBySequenceParams{
		DialogID: chatUUID,
		Sequence: lastSequence,
	})
	if err != nil {
		return false, err
	}

	_, err = r.MessagesClient.MarkAsRead(ctx, &messagesv1.MarkAsReadRequest{
		ChatId:        chatID,
		UserId:        authID,
		LastMessageId: msg.ID.String(),
	})
	if err != nil {
		return false, err
	}

	payload := model.ReadPayload{
		ChatID:       chatID,
		UserID:       authID,
		LastSequence: msg.Sequence,
	}
	data, _ := json.Marshal(payload)
	r.RedisClient.Publish(ctx, "chat:"+chatID+":read", data)

	return true, nil
}

// MessageHistory is the resolver for the messageHistory field.
func (r *queryResolver) MessageHistory(ctx context.Context, chatID string, limit int, offset int) (model.MessageHistoryResult, error) {
	resp, err := r.MessagesClient.GetHistory(ctx, &messagesv1.GetHistoryRequest{
		ChatId: chatID,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	messages := make([]*model.Message, 0, len(resp.Messages))
	for _, m := range resp.Messages {
		if mapped := helpers.MapMessageToModel(m); mapped != nil {
			messages = append(messages, mapped)
		}
	}

	return &model.MessageConnection{
		Messages: messages,
		HasMore:  len(messages) >= limit,
	}, nil
}

// DialogRead is the resolver for the dialogRead field.
func (r *queryResolver) DialogRead(ctx context.Context, chatID string) (*model.ReadPayload, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, nil
	}

	chatUUID, err := uuid.Parse(chatID)
	if err != nil {
		return nil, err
	}
	userUUID, err := uuid.Parse(authID)
	if err != nil {
		return nil, err
	}

	member, err := r.Store.GetDialogMember(ctx, dbgen.GetDialogMemberParams{
		DialogID: chatUUID,
		UserID:   userUUID,
	})
	if err != nil {
		return &model.ReadPayload{
			ChatID:       chatID,
			UserID:       authID,
			LastSequence: 0,
		}, nil
	}

	return &model.ReadPayload{
		ChatID:       chatID,
		UserID:       authID,
		LastSequence: member.LastReadSequence,
	}, nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, chatID string) (<-chan *model.Message, error) {
	out := make(chan *model.Message, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "chat:"+chatID)

	go func() {
		defer pubsub.Close()
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}
				var m model.Message
				if err := json.Unmarshal([]byte(msg.Payload), &m); err == nil {
					select {
					case out <- &m:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()
	return out, nil
}

// DialogRead is the resolver for the dialogRead field.
func (r *subscriptionResolver) DialogRead(ctx context.Context, chatID string) (<-chan *model.ReadPayload, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, fmt.Errorf("unauthorized")
	}

	readChan := make(chan *model.ReadPayload, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "chat:"+chatID+":read")

	go func() {
		defer pubsub.Close()
		defer close(readChan)
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}
				var payload model.ReadPayload
				if err := json.Unmarshal([]byte(msg.Payload), &payload); err == nil {
					select {
					case readChan <- &payload:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return readChan, nil
}

// Message returns graph.MessageResolver implementation.
func (r *Resolver) Message() graph.MessageResolver { return &messageResolver{r} }

type messageResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *messageResolver) ReplyTo(ctx context.Context, obj *model.Message) (*model.Message, error) {
	if obj == nil || obj.ReplyTo == nil || obj.ReplyTo.ID == "" {
		return nil, nil
	}

	if obj.ReplyTo.Text != "" {
		return obj.ReplyTo, nil
	}

	return loaders.LoadMessage(ctx, obj.ReplyTo.ID)
}
*/
