package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	dbgen "github.com/tr1xdev/aerogram-messenger/internal/database/sqlc/gen"
	"github.com/tr1xdev/aerogram-messenger/internal/graph"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/loaders"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	messagesv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/messages/v1"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
)

// Sender is the resolver for the sender field.
func (r *messageResolver) Sender(ctx context.Context, obj *model.Message) (*dbgen.User, error) {
	if obj == nil || obj.ID == "" {
		return nil, nil
	}

	msgUUID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, nil
	}

	dbMsg, err := r.Store.GetMessageByID(ctx, msgUUID)
	if err != nil {
		return nil, fmt.Errorf("message not found: %w", err)
	}

	return loaders.LoadUser(ctx, dbMsg.AuthorID.String())
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, chatID string, text string, isEncrypted bool, encryptionIv *string, replyToID *string) (model.SendMessageResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "Unauthorized"}, nil
	}

	resp, err := r.MessagesClient.SendMessage(ctx, &messagesv1.SendMessageRequest{
		ChatId:       chatID,
		SenderId:     authID,
		Text:         text,
		IsEncrypted:  isEncrypted,
		EncryptionIv: encryptionIv,
		ReplyToId:    replyToID,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	msg := helpers.MapMessageToModel(resp.Message)
	payload, _ := json.Marshal(msg)
	r.RedisClient.Publish(ctx, "chat:"+chatID, payload)

	return msg, nil
}

// UpdateMessage is the resolver for the updateMessage field.
func (r *mutationResolver) UpdateMessage(ctx context.Context, id string, text string) (model.SendMessageResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "Unauthorized"}, nil
	}

	resp, err := r.MessagesClient.UpdateMessage(ctx, &messagesv1.UpdateMessageRequest{
		Id:       id,
		SenderId: authID,
		Text:     text,
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	msg := helpers.MapMessageToModel(resp.Message)
	payload, _ := json.Marshal(msg)
	r.RedisClient.Publish(ctx, "chat:"+resp.Message.ChatId, payload)

	return msg, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, nil
	}

	_, err := r.MessagesClient.DeleteMessage(ctx, &messagesv1.DeleteMessageRequest{
		Id:       id,
		SenderId: authID,
	})
	return err == nil, nil
}

// MarkDialogAsRead is the resolver for the markDialogAsRead field.
func (r *mutationResolver) MarkDialogAsRead(ctx context.Context, chatID string, lastSequence int64) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, nil
	}

	payload := model.ReadPayload{
		ChatID:       chatID,
		UserID:       authID,
		LastSequence: lastSequence,
	}
	data, _ := json.Marshal(payload)
	r.RedisClient.Publish(ctx, "chat:"+chatID+":read", data)

	return true, nil
}

// MessageHistory is the resolver for the messageHistory field.
func (r *queryResolver) MessageHistory(ctx context.Context, chatID string, limit int, offset int) (model.MessageHistoryResult, error) {
	resp, err := r.MessagesClient.GetHistory(ctx, &messagesv1.GetHistoryRequest{
		ChatId: chatID,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		return &model.InternalError{Message: err.Error()}, nil
	}

	messages := make([]*model.Message, len(resp.Messages))
	for i, m := range resp.Messages {
		messages[i] = helpers.MapMessageToModel(m)
	}

	return &model.MessageConnection{
		Messages: messages,
		HasMore:  len(messages) >= limit,
	}, nil
}

// DialogRead is the resolver for the dialogRead field.
func (r *queryResolver) DialogRead(ctx context.Context, chatID string) (*model.ReadPayload, error) {
	authID := middleware.GetUserID(ctx)
	return &model.ReadPayload{
		ChatID:       chatID,
		UserID:       authID,
		LastSequence: 0,
	}, nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, chatID string) (<-chan *model.Message, error) {
	out := make(chan *model.Message, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "chat:"+chatID)

	go func() {
		defer pubsub.Close()
		defer close(out)
		for msg := range pubsub.Channel() {
			var m model.Message
			if err := json.Unmarshal([]byte(msg.Payload), &m); err == nil {
				out <- &m
			}
		}
	}()
	return out, nil
}

// DialogRead is the resolver for the dialogRead field.
func (r *subscriptionResolver) DialogRead(ctx context.Context, chatID string) (<-chan *model.ReadPayload, error) {
	out := make(chan *model.ReadPayload, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "chat:"+chatID+":read")

	go func() {
		defer pubsub.Close()
		defer close(out)
		for msg := range pubsub.Channel() {
			var p model.ReadPayload
			if err := json.Unmarshal([]byte(msg.Payload), &p); err == nil {
				out <- &p
			}
		}
	}()
	return out, nil
}

// Message returns graph.MessageResolver implementation.
func (r *Resolver) Message() graph.MessageResolver { return &messageResolver{r} }

type messageResolver struct{ *Resolver }
