package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
	dbgen "github.com/tr1xdev/aerogram-messenger/internal/database/sqlc/gen"
	"github.com/tr1xdev/aerogram-messenger/internal/graph"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/loaders"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	authv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/auth/v1"
	chatv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/chat/v1"
	userv1 "github.com/tr1xdev/aerogram-messenger/internal/grpc/gen/user/v1"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
	"github.com/tr1xdev/aerogram-messenger/internal/repositories"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// UploadAvatar is the resolver for the uploadAvatar field.
func (r *mutationResolver) UploadAvatar(ctx context.Context, file graphql.Upload) (*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized access")
	}

	uid, err := uuid.Parse(authID)
	if err != nil {
		return nil, errors.New("invalid user id")
	}

	ext := filepath.Ext(file.Filename)
	fileKey := fmt.Sprintf("avatars/%s/avatar_%d%s", authID, time.Now().Unix(), ext)

	_, err = r.Storage.UploadFile(ctx, fileKey, file.File, file.ContentType)
	if err != nil {
		return nil, fmt.Errorf("failed to upload image to storage: %w", err)
	}

	updatedUser, err := r.Store.UpdateUserPhoto(ctx, dbgen.UpdateUserPhotoParams{
		ID:       uid,
		PhotoUrl: sql.NullString{String: fileKey, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update user photo in database: %w", err)
	}

	return &updatedUser, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized access")
	}
	uid, err := uuid.Parse(authID)
	if err != nil {
		return nil, errors.New("invalid user id")
	}

	params := dbgen.UpdateUserParams{
		ID:             uid,
		FirstName:      helpers.ToNullString(input.FirstName),
		LastName:       helpers.ToNullString(input.LastName),
		Username:       helpers.ToNullString(input.Username),
		PhotoUrl:       helpers.ToNullString(input.PhotoURL),
		BotDescription: helpers.ToNullString(input.BotDescription),
	}

	if input.BotCommands != nil && *input.BotCommands != "" {
		params.BotCommands = pqtype.NullRawMessage{
			RawMessage: json.RawMessage(*input.BotCommands),
			Valid:      true,
		}
	}

	_, err = r.Store.UpdateUser(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	return loaders.LoadUser(ctx, authID)
}

// CreateBot is the resolver for the createBot field.
func (r *mutationResolver) CreateBot(ctx context.Context, username string, firstName string, lastName *string, description *string, commands *string) (model.CreateBotResult, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return &model.ForbiddenError{Message: "Unauthorized"}, nil
	}

	resp, err := r.UserClient.CreateBot(ctx, &userv1.CreateBotRequest{
		OwnerId:     authID,
		Username:    username,
		FirstName:   firstName,
		LastName:    lastName,
		Description: description,
		Commands:    commands,
	})

	if err != nil {
		st, ok := status.FromError(err)
		if ok {
			switch st.Code() {
			case codes.ResourceExhausted:
				return &model.InternalError{Message: "Limit exceeded: " + st.Message()}, nil
			case codes.FailedPrecondition:
				return &model.InternalError{Message: st.Message()}, nil
			case codes.InvalidArgument:
				field := "input"
				return &model.ValidationError{Field: &field, Message: st.Message()}, nil
			}
		}
		return &model.InternalError{Message: "Service error"}, nil
	}

	botProto := resp.GetUser()
	botID, _ := uuid.Parse(botProto.Id)

	botUser := dbgen.User{
		ID:        botID,
		FirstName: botProto.FirstName,
		IsBot:     true,
	}

	tokenResp, err := r.AuthClient.CreateBotToken(ctx, &authv1.CreateBotTokenRequest{
		BotId: botProto.Id,
	})
	if err != nil {
		return &model.InternalError{Message: "Failed to generate bot token"}, nil
	}

	return &model.CreateBotPayload{
		BotToken: tokenResp.AccessToken,
		User:     &botUser,
	}, nil
}

// UpdateBot is the resolver for the updateBot field.
func (r *mutationResolver) UpdateBot(ctx context.Context, id string, input model.UpdateUserInput) (*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	_, rawID, err := helpers.DecodeGlobalID(id)
	if err != nil {
		rawID = id
	}

	botUUID, err := uuid.Parse(rawID)
	if err != nil {
		return nil, errors.New("invalid bot id")
	}

	if input.Username != nil {
		trimmed := strings.TrimSpace(*input.Username)
		if !strings.HasSuffix(strings.ToLower(trimmed), "bot") {
			return nil, errors.New("bot username must end with 'bot'")
		}
	}

	ownerUUID, err := uuid.Parse(authID)
	if err != nil {
		return nil, errors.New("invalid owner id")
	}

	params := dbgen.UpdateBotParams{
		ID:             botUUID,
		BotOwnerID:     uuid.NullUUID{UUID: ownerUUID, Valid: true},
		FirstName:      helpers.ToNullString(input.FirstName),
		LastName:       helpers.ToNullString(input.LastName),
		Username:       helpers.ToNullString(input.Username),
		PhotoUrl:       helpers.ToNullString(input.PhotoURL),
		BotDescription: helpers.ToNullString(input.BotDescription),
	}

	if input.BotCommands != nil && *input.BotCommands != "" {
		params.BotCommands = pqtype.NullRawMessage{
			RawMessage: json.RawMessage(*input.BotCommands),
			Valid:      true,
		}
	}

	user, err := r.Store.UpdateBot(ctx, params)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, errors.New("bot not found or access denied")
		}
		return nil, fmt.Errorf("failed to update bot: %w", err)
	}

	return &user, nil
}

// DeleteBot is the resolver for the deleteBot field.
func (r *mutationResolver) DeleteBot(ctx context.Context, id string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, errors.New("unauthorized")
	}

	_, rawID, err := helpers.DecodeGlobalID(id)
	if err != nil {
		rawID = id
	}

	botUUID, err := uuid.Parse(rawID)
	if err != nil {
		return false, errors.New("invalid bot id")
	}

	ownerUUID, err := uuid.Parse(authID)
	if err != nil {
		return false, errors.New("invalid owner id")
	}

	err = r.Store.DeleteBot(ctx, dbgen.DeleteBotParams{
		ID:         botUUID,
		BotOwnerID: uuid.NullUUID{UUID: ownerUUID, Valid: true},
	})
	if err != nil {
		return false, fmt.Errorf("failed to delete bot: %w", err)
	}

	return true, nil
}

// RotateBotToken is the resolver for the rotateBotToken field.
func (r *mutationResolver) RotateBotToken(ctx context.Context, id string) (string, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return "", errors.New("unauthorized")
	}

	_, rawID, err := helpers.DecodeGlobalID(id)
	if err != nil {
		rawID = id
	}

	botUUID, err := uuid.Parse(rawID)
	if err != nil {
		return "", errors.New("invalid bot id")
	}

	bot, err := r.Store.GetUserByID(ctx, botUUID)
	if err != nil {
		return "", errors.New("bot not found")
	}

	if !bot.BotOwnerID.Valid || bot.BotOwnerID.UUID.String() != authID {
		return "", errors.New("access denied: you are not the owner")
	}

	resp, err := r.AuthClient.CreateBotToken(ctx, &authv1.CreateBotTokenRequest{
		BotId: rawID,
	})
	if err != nil {
		return "", fmt.Errorf("failed to rotate token: %w", err)
	}

	return resp.AccessToken, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	kind, uuidStr, err := helpers.DecodeGlobalID(id)
	if err != nil {
		return nil, errors.New("invalid node id")
	}

	switch kind {
	case "User":
		return loaders.LoadUser(ctx, uuidStr)
	case "Chat":
		authID := middleware.GetUserID(ctx)
		if authID == "" {
			return nil, errors.New("unauthorized")
		}
		resp, err := r.ChatClient.GetChat(ctx, &chatv1.GetChatRequest{
			ChatId: &uuidStr,
			UserId: authID,
		})
		if err != nil {
			return nil, helpers.MapGRPCError(err)
		}

		// Убираем r.Store, оставляем только (ctx, authID, pbChat)
		return r.Enricher.EnrichChat(ctx, authID, resp.Chat)
	default:
		return nil, fmt.Errorf("unsupported node type: %s", kind)
	}
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}
	return loaders.LoadUser(ctx, authID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*dbgen.User, error) {
	_, rawID, err := helpers.DecodeGlobalID(id)
	if err != nil {
		rawID = id
	}
	return loaders.LoadUser(ctx, rawID)
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*dbgen.User, error) {
	_, rawID, err := helpers.DecodeGlobalID(id)
	if err != nil {
		rawID = id
	}
	return loaders.LoadUser(ctx, rawID)
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, username string) ([]*dbgen.User, error) {
	cleanQuery := strings.TrimSpace(username)
	if len(cleanQuery) < 3 {
		return []*dbgen.User{}, nil
	}
	users, err := r.Store.SearchUsersByUsername(ctx, cleanQuery)
	if err != nil {
		return nil, err
	}
	result := make([]*dbgen.User, len(users))
	for i := range users {
		result[i] = &users[i]
	}
	return result, nil
}

// MyBots is the resolver for the myBots field.
func (r *queryResolver) MyBots(ctx context.Context) ([]*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}
	ownerUUID, err := uuid.Parse(authID)
	if err != nil {
		return nil, errors.New("invalid user id")
	}
	bots, err := r.Store.GetBotsByOwnerID(ctx, uuid.NullUUID{
		UUID:  ownerUUID,
		Valid: true,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch bots: %w", err)
	}
	result := make([]*dbgen.User, len(bots))
	for i := range bots {
		result[i] = &bots[i]
	}
	return result, nil
}

// UserStatusChanged is the resolver for the userStatusChanged field.
func (r *subscriptionResolver) UserStatusChanged(ctx context.Context, chatID string) (<-chan *model.UserStatusPayload, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	statusChan := make(chan *model.UserStatusPayload, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "presence:updates")

	go func() {
		defer func() {
			pubsub.Close()
			close(statusChan)
		}()

		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}

				var ps repositories.PresenceStatus
				if err := json.Unmarshal([]byte(msg.Payload), &ps); err != nil {
					continue
				}

				payload := &model.UserStatusPayload{
					UserID: helpers.EncodeGlobalID("User", ps.UserID.String()),
					Status: ps.Status,
				}

				if ps.LastSeen != "" {
					ls := ps.LastSeen
					payload.LastSeen = &ls
				}

				select {
				case statusChan <- payload:
				case <-ctx.Done():
					return
				default:
				}
			}
		}
	}()

	return statusChan, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *dbgen.User) (string, error) {
	return helpers.EncodeGlobalID("User", obj.ID.String()), nil
}

// Email is the resolver for the email field.
func (r *userResolver) Email(ctx context.Context, obj *dbgen.User) (*string, error) {
	if obj.Email.Valid {
		return &obj.Email.String, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		return nil, nil
	}
	return helpers.ToStringPtr(u.Email), nil
}

// FirstName is the resolver for the firstName field.
func (r *userResolver) FirstName(ctx context.Context, obj *dbgen.User) (string, error) {
	if obj.FirstName != "" {
		return obj.FirstName, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		return "User", nil
	}
	return u.FirstName, nil
}

// LastName is the resolver for the lastName field.
func (r *userResolver) LastName(ctx context.Context, obj *dbgen.User) (*string, error) {
	if obj.LastName.Valid {
		return &obj.LastName.String, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		return nil, nil
	}
	return helpers.ToStringPtr(u.LastName), nil
}

// DisplayName is the resolver for the displayName field.
func (r *userResolver) DisplayName(ctx context.Context, obj *dbgen.User) (*string, error) {
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		name := obj.FirstName
		return &name, nil
	}
	full := u.FirstName
	if u.LastName.Valid && u.LastName.String != "" {
		full += " " + u.LastName.String
	}
	return &full, nil
}

// Username is the resolver for the username field.
func (r *userResolver) Username(ctx context.Context, obj *dbgen.User) (*string, error) {
	if obj.Username.Valid {
		return &obj.Username.String, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		return nil, nil
	}
	return helpers.ToStringPtr(u.Username), nil
}

// PhotoURL is the resolver for the photoUrl field.
func (r *userResolver) PhotoURL(ctx context.Context, obj *dbgen.User) (*string, error) {
	var path string

	if obj.PhotoUrl.Valid && obj.PhotoUrl.String != "" {
		path = obj.PhotoUrl.String
	} else {
		u, err := loaders.LoadUser(ctx, obj.ID.String())
		if err != nil || u == nil || !u.PhotoUrl.Valid || u.PhotoUrl.String == "" {
			return nil, nil
		}
		path = u.PhotoUrl.String
	}

	presignedURL, err := r.Storage.GetPresignedURL(ctx, path, 24*time.Hour)
	if err != nil {
		return nil, nil
	}

	return &presignedURL, nil
}

// Bio is the resolver for the bio field.
func (r *userResolver) Bio(ctx context.Context, obj *dbgen.User) (*string, error) {
	if obj.Bio.Valid {
		return &obj.Bio.String, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		return nil, nil
	}
	return helpers.ToStringPtr(u.Bio), nil
}

// Status is the resolver for the status field.
func (r *userResolver) Status(ctx context.Context, obj *dbgen.User) (string, error) {
	status, err := loaders.LoadPresence(ctx, obj.ID.String())
	if err != nil {
		return "offline", nil
	}
	return status, nil
}

// IsTyping is the resolver for the isTyping field.
func (r *userResolver) IsTyping(ctx context.Context, obj *dbgen.User) (bool, error) {
	return false, nil
}

// BotDescription is the resolver for the botDescription field.
func (r *userResolver) BotDescription(ctx context.Context, obj *dbgen.User) (*string, error) {
	if obj.BotDescription.Valid {
		return &obj.BotDescription.String, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil {
		return nil, nil
	}
	return helpers.ToStringPtr(u.BotDescription), nil
}

// BotCommands is the resolver for the botCommands field.
func (r *userResolver) BotCommands(ctx context.Context, obj *dbgen.User) (*string, error) {
	if obj.BotCommands.Valid {
		str := string(obj.BotCommands.RawMessage)
		return &str, nil
	}
	u, err := loaders.LoadUser(ctx, obj.ID.String())
	if err != nil || !u.BotCommands.Valid {
		return nil, nil
	}
	str := string(u.BotCommands.RawMessage)
	return &str, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
