package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	dbgen "github.com/tr1xdev/aerogram-messenger/internal/database/sqlc/gen"
	"github.com/tr1xdev/aerogram-messenger/internal/graph"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/helpers"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/loaders"
	"github.com/tr1xdev/aerogram-messenger/internal/graph/model"
	"github.com/tr1xdev/aerogram-messenger/internal/middleware"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized access")
	}
	uid, err := uuid.Parse(authID)
	if err != nil {
		return nil, errors.New("invalid user id")
	}

	_, err = r.Store.UpdateUser(ctx, dbgen.UpdateUserParams{
		ID:               uid,
		FirstName:        helpers.ToNullString(input.FirstName),
		LastName:         helpers.ToNullString(input.LastName),
		Username:         helpers.ToNullString(input.Username),
		PublicKey:        helpers.ToNullString(input.PublicKey),
		EncryptedPrivKey: helpers.ToNullString(input.EncryptedPrivKey),
		EncryptionIv:     helpers.ToNullString(input.EncryptionIv),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	return loaders.LoadUser(ctx, authID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	return loaders.LoadUser(ctx, authID)
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*dbgen.User, error) {
	return loaders.LoadUser(ctx, id)
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, username string) ([]*dbgen.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	users, err := r.Store.SearchUsersByUsername(ctx, "%"+strings.ToLower(username)+"%")
	if err != nil {
		return nil, err
	}

	result := make([]*dbgen.User, len(users))
	for i := range users {
		result[i] = &users[i]
	}
	return result, nil
}

// UserStatusChanged is the resolver for the userStatusChanged field.
func (r *subscriptionResolver) UserStatusChanged(ctx context.Context, chatID string) (<-chan *model.UserStatusPayload, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	statusChan := make(chan *model.UserStatusPayload, 1)
	pubsub := r.RedisClient.Subscribe(ctx, "presence:updates")

	go func() {
		defer pubsub.Close()
		defer close(statusChan)

		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}

				var payload struct {
					UserID string `json:"userId"`
					Status string `json:"status"`
					ChatID string `json:"chatId"`
				}

				if err := json.Unmarshal([]byte(msg.Payload), &payload); err != nil {
					continue
				}

				if payload.ChatID != chatID {
					continue
				}

				select {
				case statusChan <- &model.UserStatusPayload{
					UserID: payload.UserID,
					Status: payload.Status,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return statusChan, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *dbgen.User) (string, error) {
	return obj.ID.String(), nil
}

// LastName is the resolver for the last_name field.
func (r *userResolver) LastName(ctx context.Context, obj *dbgen.User) (*string, error) {
	return helpers.ToStringPtr(obj.LastName), nil
}

// Username is the resolver for the username field.
func (r *userResolver) Username(ctx context.Context, obj *dbgen.User) (*string, error) {
	return helpers.ToStringPtr(obj.Username), nil
}

// Status is the resolver for the status field.
func (r *userResolver) Status(ctx context.Context, obj *dbgen.User) (string, error) {
	// Тут можно прикрутить логику из Redis, но пока просто заглушка, чтобы не падало
	return "offline", nil
}

// PublicKey is the resolver for the publicKey field.
func (r *userResolver) PublicKey(ctx context.Context, obj *dbgen.User) (*string, error) {
	return helpers.ToStringPtr(obj.PublicKey), nil
}

// EncryptedPrivKey is the resolver for the encryptedPrivKey field.
func (r *userResolver) EncryptedPrivKey(ctx context.Context, obj *dbgen.User) (*string, error) {
	return helpers.ToStringPtr(obj.EncryptedPrivKey), nil
}

// EncryptionIv is the resolver for the encryptionIv field.
func (r *userResolver) EncryptionIv(ctx context.Context, obj *dbgen.User) (*string, error) {
	return helpers.ToStringPtr(obj.EncryptionIv), nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
