// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/aerogram-org/aerogram-api/internal/models"
)

type AuthPayload struct {
	UserID *string `json:"user_id,omitempty"`
}

type Chat struct {
	ID               string            `json:"id"`
	Type             ChatType          `json:"type"`
	Slug             *string           `json:"slug,omitempty"`
	Title            string            `json:"title"`
	PhotoURL         *string           `json:"photoUrl,omitempty"`
	MembersCount     int               `json:"membersCount"`
	UnreadCount      int               `json:"unreadCount"`
	IsPinned         bool              `json:"isPinned"`
	LastMessage      *models.Message   `json:"lastMessage,omitempty"`
	LastReadSequence int64             `json:"lastReadSequence"`
	Members          []*ChatMember     `json:"members,omitempty"`
	Messages         []*models.Message `json:"messages"`
}

type ChatMember struct {
	User             *models.User `json:"user"`
	LastReadSequence int64        `json:"lastReadSequence"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type ReadPayload struct {
	ChatID       string `json:"chatID"`
	UserID       string `json:"userID"`
	LastSequence int64  `json:"lastSequence"`
}

type SignUpInput struct {
	Username  *string `json:"username,omitempty"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName string  `json:"first_name"`
	LastName  *string `json:"last_name,omitempty"`
}

type Subscription struct {
}

type UpdateUserInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Username  *string `json:"username,omitempty"`
	PublicKey *string `json:"publicKey,omitempty"`
}

type UserStatusPayload struct {
	UserID string `json:"userId"`
	Status string `json:"status"`
}

type VerifyEmailInput struct {
	UserID string `json:"userID"`
	Code   string `json:"code"`
}

type VerifyEmailPayload struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type ChatType string

const (
	ChatTypePrivate ChatType = "PRIVATE"
	ChatTypeGroup   ChatType = "GROUP"
	ChatTypeChannel ChatType = "CHANNEL"
)

var AllChatType = []ChatType{
	ChatTypePrivate,
	ChatTypeGroup,
	ChatTypeChannel,
}

func (e ChatType) IsValid() bool {
	switch e {
	case ChatTypePrivate, ChatTypeGroup, ChatTypeChannel:
		return true
	}
	return false
}

func (e ChatType) String() string {
	return string(e)
}

func (e *ChatType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChatType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChatType", str)
	}
	return nil
}

func (e ChatType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChatType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChatType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
