// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	dbgen "github.com/tr1xdev/aerogram-messenger/internal/database/sqlc/gen"
)

type ChatResult interface {
	IsChatResult()
}

type CreateBotResult interface {
	IsCreateBotResult()
}

type CreateChatResult interface {
	IsCreateChatResult()
}

type DeleteChatResult interface {
	IsDeleteChatResult()
}

type Error interface {
	IsError()
	GetMessage() string
}

type MessageHistoryResult interface {
	IsMessageHistoryResult()
}

type MyChatsResult interface {
	IsMyChatsResult()
}

type PinChatResult interface {
	IsPinChatResult()
}

type SendMessageResult interface {
	IsSendMessageResult()
}

type AuthPayload struct {
	UserID               string  `json:"userId"`
	AccessToken          *string `json:"accessToken,omitempty"`
	RefreshToken         *string `json:"refreshToken,omitempty"`
	RequiresVerification bool    `json:"requiresVerification"`
}

type Chat struct {
	ID               string        `json:"id"`
	Type             ChatType      `json:"type"`
	Slug             *string       `json:"slug,omitempty"`
	Title            string        `json:"title"`
	PhotoURL         *string       `json:"photoUrl,omitempty"`
	MembersCount     int           `json:"membersCount"`
	UnreadCount      int           `json:"unreadCount"`
	IsPinned         bool          `json:"isPinned"`
	LastMessage      *Message      `json:"lastMessage,omitempty"`
	LastReadSequence int64         `json:"lastReadSequence"`
	Members          []*ChatMember `json:"members,omitempty"`
	Messages         []*Message    `json:"messages"`
	CreatedAt        string        `json:"createdAt"`
}

func (Chat) IsChatResult() {}

func (Chat) IsCreateChatResult() {}

type ChatList struct {
	Chats []*Chat `json:"chats"`
}

func (ChatList) IsMyChatsResult() {}

type ChatMember struct {
	User             *dbgen.User `json:"user"`
	LastReadSequence int64       `json:"lastReadSequence"`
}

type CreateBotPayload struct {
	BotToken string      `json:"botToken"`
	User     *dbgen.User `json:"user"`
}

func (CreateBotPayload) IsCreateBotResult() {}

type ForbiddenError struct {
	Message string `json:"message"`
}

func (ForbiddenError) IsChatResult() {}

func (ForbiddenError) IsMyChatsResult() {}

func (ForbiddenError) IsCreateChatResult() {}

func (ForbiddenError) IsPinChatResult() {}

func (ForbiddenError) IsDeleteChatResult() {}

func (ForbiddenError) IsError()                {}
func (this ForbiddenError) GetMessage() string { return this.Message }

func (ForbiddenError) IsSendMessageResult() {}

func (ForbiddenError) IsMessageHistoryResult() {}

func (ForbiddenError) IsCreateBotResult() {}

type InternalError struct {
	Message string `json:"message"`
}

func (InternalError) IsChatResult() {}

func (InternalError) IsMyChatsResult() {}

func (InternalError) IsCreateChatResult() {}

func (InternalError) IsPinChatResult() {}

func (InternalError) IsDeleteChatResult() {}

func (InternalError) IsError()                {}
func (this InternalError) GetMessage() string { return this.Message }

func (InternalError) IsSendMessageResult() {}

func (InternalError) IsMessageHistoryResult() {}

func (InternalError) IsCreateBotResult() {}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Message struct {
	ID            string      `json:"id"`
	ChatID        string      `json:"chatId"`
	Sender        *dbgen.User `json:"sender,omitempty"`
	Text          string      `json:"text"`
	SentAt        string      `json:"sentAt"`
	Sequence      int64       `json:"sequence"`
	IsEdited      bool        `json:"isEdited"`
	IsEncrypted   bool        `json:"isEncrypted"`
	EncryptionIv  *string     `json:"encryptionIv,omitempty"`
	ReplyTo       *Message    `json:"replyTo,omitempty"`
	ForwardedFrom *Message    `json:"forwardedFrom,omitempty"`
}

func (Message) IsSendMessageResult() {}

type MessageConnection struct {
	Messages []*Message `json:"messages"`
	HasMore  bool       `json:"hasMore"`
}

func (MessageConnection) IsMessageHistoryResult() {}

type Mutation struct {
}

type NotFoundError struct {
	Message string `json:"message"`
}

func (NotFoundError) IsChatResult() {}

func (NotFoundError) IsError()                {}
func (this NotFoundError) GetMessage() string { return this.Message }

func (NotFoundError) IsMessageHistoryResult() {}

type Query struct {
}

type ReadPayload struct {
	ChatID       string `json:"chatId"`
	UserID       string `json:"userId"`
	LastSequence int64  `json:"lastSequence"`
}

type SignUpInput struct {
	Username  *string `json:"username,omitempty"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  *string `json:"lastName,omitempty"`
}

type Subscription struct {
}

type SuccessResult struct {
	Success bool `json:"success"`
}

func (SuccessResult) IsPinChatResult() {}

func (SuccessResult) IsDeleteChatResult() {}

type TypingPayload struct {
	UserID   string `json:"userId"`
	IsTyping bool   `json:"isTyping"`
}

type UpdateUserInput struct {
	FirstName        *string `json:"firstName,omitempty"`
	LastName         *string `json:"lastName,omitempty"`
	Username         *string `json:"username,omitempty"`
	Bio              *string `json:"bio,omitempty"`
	PublicKey        *string `json:"publicKey,omitempty"`
	EncryptedPrivKey *string `json:"encryptedPrivKey,omitempty"`
	EncryptionIv     *string `json:"encryptionIv,omitempty"`
	PhotoURL         *string `json:"photoUrl,omitempty"`
	BotDescription   *string `json:"botDescription,omitempty"`
	BotCommands      *string `json:"botCommands,omitempty"`
}

type UserStatusPayload struct {
	UserID   string  `json:"userId"`
	Status   string  `json:"status"`
	LastSeen *string `json:"lastSeen,omitempty"`
}

type ValidationError struct {
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
}

func (ValidationError) IsCreateChatResult() {}

func (ValidationError) IsError()                {}
func (this ValidationError) GetMessage() string { return this.Message }

func (ValidationError) IsSendMessageResult() {}

func (ValidationError) IsCreateBotResult() {}

type VerifyEmailInput struct {
	UserID string `json:"userID"`
	Code   string `json:"code"`
}

type ChatType string

const (
	ChatTypePrivate ChatType = "PRIVATE"
	ChatTypeGroup   ChatType = "GROUP"
	ChatTypeChannel ChatType = "CHANNEL"
)

var AllChatType = []ChatType{
	ChatTypePrivate,
	ChatTypeGroup,
	ChatTypeChannel,
}

func (e ChatType) IsValid() bool {
	switch e {
	case ChatTypePrivate, ChatTypeGroup, ChatTypeChannel:
		return true
	}
	return false
}

func (e ChatType) String() string {
	return string(e)
}

func (e *ChatType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChatType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChatType", str)
	}
	return nil
}

func (e ChatType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChatType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChatType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
