services:
    api:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: aerogram-api
        restart: always
        ports:
            - "${HTTP_PORT:-8080}:8080/tcp"
            - "${HTTP_PORT:-8080}:8080/udp"
            - "${GRPC_PORT:-50051}:50051/tcp"
        env_file: .env
        environment:
            - DB_HOST=postgres
            - REDIS_HOST=redis
            - S3_ENDPOINT=http://minio:9000
        volumes:
            - ./assets:/app/assets:ro
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            minio:
                condition: service_started
        networks:
            - aerogram-net

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
            args:
                - VITE_API_URL=${VITE_API_URL}
                - VITE_WS_URL=${VITE_WS_URL}
        container_name: aerogram-ui
        restart: always
        ports:
            - "3000:80"
            - "3443:3443"
            - "3443:3443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - aerogram-net
        depends_on:
            - api

    postgres:
        image: postgres:15-alpine
        container_name: aerogram-db
        shm_size: 128mb
        ports:
            - "5432:5432"
        env_file: .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - aerogram-net

    redis:
        image: redis:7.2-alpine
        container_name: aerogram-redis
        ports:
            - "6379:6379"
        env_file: .env
        command: redis-server --requirepass ${REDIS_PASSWORD}
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - aerogram-net

    minio:
        image: minio/minio
        container_name: aerogram-s3
        ports:
            - "9000:9000"
            - "9001:9001"
        env_file: .env
        environment:
            MINIO_ROOT_USER: ${S3_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
        command: server /data --console-address ":9001"
        volumes:
            - s3data:/data
        networks:
            - aerogram-net

networks:
    aerogram-net:
        driver: bridge

volumes:
    pgdata:
    s3data:
    caddy_data:
    caddy_config:
