package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/aerogram-org/aerogram-api/internal/graph/model"
	authpb "github.com/aerogram-org/aerogram-api/internal/grpc/gen/auth/v1"
	chatpb "github.com/aerogram-org/aerogram-api/internal/grpc/gen/chat/v1"
	messagespb "github.com/aerogram-org/aerogram-api/internal/grpc/gen/messages/v1"
	"github.com/aerogram-org/aerogram-api/internal/middleware"
	"github.com/aerogram-org/aerogram-api/internal/models"
)

// ChatID is the resolver for the chatId field.
func (r *messageResolver) ChatID(ctx context.Context, obj *models.Message) (string, error) {
	return obj.DialogID, nil
}

// Text is the resolver for the text field.
func (r *messageResolver) Text(ctx context.Context, obj *models.Message) (string, error) {
	return obj.Content, nil
}

// SentAt is the resolver for the sentAt field.
func (r *messageResolver) SentAt(ctx context.Context, obj *models.Message) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// IsRead is the resolver for the isRead field.
func (r *messageResolver) IsRead(ctx context.Context, obj *models.Message) (bool, error) {
	authID := middleware.GetUserID(ctx)

	if obj.AuthorID == authID {
		var otherMember models.DialogMember
		err := r.db.Where("dialog_id = ? AND user_id != ?", obj.DialogID, authID).First(&otherMember).Error
		if err == nil {
			if !obj.CreatedAt.After(otherMember.LastReadAt) {
				return true, nil
			}
		}
		return obj.ViewsCount > 0, nil
	}

	var myMember models.DialogMember
	err := r.db.Where("dialog_id = ? AND user_id = ?", obj.DialogID, authID).First(&myMember).Error
	if err != nil {
		return false, nil
	}

	return !obj.CreatedAt.After(myMember.LastReadAt), nil
}

// ReplyTo is the resolver for the replyTo field.
func (r *messageResolver) ReplyTo(ctx context.Context, obj *models.Message) (*models.Message, error) {
	if obj.ReplyToID == nil || *obj.ReplyToID == "" {
		return nil, nil
	}
	var msg models.Message
	if err := r.db.First(&msg, "id = ?", *obj.ReplyToID).Error; err != nil {
		return nil, nil
	}
	return &msg, nil
}

// ForwardedFrom is the resolver for the forwardedFrom field.
func (r *messageResolver) ForwardedFrom(ctx context.Context, obj *models.Message) (*models.Message, error) {
	if obj.ForwardFromID == nil || *obj.ForwardFromID == "" {
		return nil, nil
	}
	var msg models.Message
	if err := r.db.First(&msg, "id = ?", *obj.ForwardFromID).Error; err != nil {
		return nil, nil
	}
	return &msg, nil
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.AuthPayload, error) {
	req := &authpb.SignUpRequest{
		Email:     input.Email,
		FirstName: input.FirstName,
		Password:  input.Password,
		LastName:  input.LastName,
		Username:  input.Username,
	}
	resp, err := r.authClient.SignUp(ctx, req)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{UserID: &resp.UserId}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	resp, err := r.authClient.Login(ctx, &authpb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{UserID: &resp.UserId}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input model.VerifyEmailInput) (*model.VerifyEmailPayload, error) {
	resp, err := r.authClient.VerifyEmail(ctx, &authpb.VerifyEmailRequest{
		UserId: input.UserID,
		Code:   input.Code,
	})
	if err != nil {
		return nil, err
	}
	return &model.VerifyEmailPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*models.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}
	updates := make(map[string]interface{})
	if input.FirstName != nil {
		updates["first_name"] = *input.FirstName
	}
	if input.LastName != nil {
		updates["last_name"] = *input.LastName
	}
	if input.Username != nil {
		updates["username"] = *input.Username
	}

	if len(updates) == 0 {
		return r.userRepo.GetByID(authID)
	}
	return r.userRepo.UpdateProfile(authID, updates)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.VerifyEmailPayload, error) {
	resp, err := r.authClient.RefreshToken(ctx, &authpb.RefreshTokenRequest{RefreshToken: token})
	if err != nil {
		return nil, err
	}
	return &model.VerifyEmailPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, typeArg model.ChatType, participantIds []string, slug *string, title *string) (*model.Chat, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	req := &chatpb.CreateChatRequest{
		Type:           chatpb.ChatType(chatpb.ChatType_value["CHAT_TYPE_"+string(typeArg)]),
		ParticipantIds: participantIds,
		CreatorId:      authID,
		Title:          title,
		Slug:           slug,
	}
	resp, err := r.chatClient.CreateChat(ctx, req)
	if err != nil {
		return nil, err
	}

	return r.enrichChat(ctx, authID, resp.Chat)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, chatID string, text string, replyToID *string) (*models.Message, error) {
	authID := middleware.GetUserID(ctx)
	resp, err := r.messagesClient.SendMessage(ctx, &messagespb.SendMessageRequest{
		ChatId:    chatID,
		SenderId:  authID,
		Text:      text,
		ReplyToId: replyToID,
	})
	if err != nil {
		return nil, err
	}

	user, _ := r.userRepo.GetByID(authID)
	sentAt, _ := time.Parse(time.RFC3339, resp.Message.SentAt)

	msg := &models.Message{
		ID:        resp.Message.Id,
		DialogID:  resp.Message.ChatId,
		AuthorID:  resp.Message.SenderId,
		Content:   resp.Message.Text,
		CreatedAt: sentAt,
		ReplyToID: resp.Message.ReplyToId,
		Sender:    user,
	}

	payload, _ := json.Marshal(msg)
	r.redisClient.Publish(ctx, "chat_updates:"+chatID, payload)

	return msg, nil
}

// UpdateMessage is the resolver for the updateMessage field.
func (r *mutationResolver) UpdateMessage(ctx context.Context, id string, text string) (*models.Message, error) {
	authID := middleware.GetUserID(ctx)
	resp, err := r.messagesClient.UpdateMessage(ctx, &messagespb.UpdateMessageRequest{
		Id:       id,
		SenderId: authID,
		Text:     text,
	})
	if err != nil {
		return nil, err
	}
	return &models.Message{ID: resp.Message.Id, Content: resp.Message.Text}, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	resp, err := r.messagesClient.DeleteMessage(ctx, &messagespb.DeleteMessageRequest{
		Id:       id,
		SenderId: authID,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// PinChat is the resolver for the pinChat field.
func (r *mutationResolver) PinChat(ctx context.Context, id string, pinned bool) (bool, error) {
	authID := middleware.GetUserID(ctx)
	resp, err := r.chatClient.PinChat(ctx, &chatpb.PinChatRequest{
		ChatId: id,
		UserId: authID,
		Pinned: pinned,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// CreateDirectChat is the resolver for the createDirectChat field.
func (r *mutationResolver) CreateDirectChat(ctx context.Context, userID string) (*model.Chat, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}
	if authID == userID {
		return nil, errors.New("cannot create chat with yourself")
	}

	req := &chatpb.CreateChatRequest{
		Type:           chatpb.ChatType_CHAT_TYPE_PRIVATE,
		ParticipantIds: []string{authID, userID},
		CreatorId:      authID,
	}
	resp, err := r.chatClient.CreateChat(ctx, req)
	if err != nil {
		return nil, err
	}

	return r.enrichChat(ctx, authID, resp.Chat)
}

// SendTypingEvent is the resolver for the sendTypingEvent field.
func (r *mutationResolver) SendTypingEvent(ctx context.Context, chatID string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	user, err := r.userRepo.GetByID(authID)
	if err != nil {
		return false, err
	}
	payload, _ := json.Marshal(map[string]string{
		"userID":   authID,
		"username": user.Username,
	})
	r.redisClient.Publish(ctx, "typing:"+chatID, payload)
	return true, nil
}

// MarkAsRead is the resolver for the markAsRead field.
func (r *mutationResolver) MarkAsRead(ctx context.Context, chatID string, lastMessageID string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	now := time.Now()

	err := r.db.Model(&models.DialogMember{}).
		Where("dialog_id = ? AND user_id = ?", chatID, authID).
		Update("last_read_at", now).Error
	if err != nil {
		return false, err
	}

	r.db.Model(&models.Message{}).
		Where("dialog_id = ? AND author_id != ? AND views_count = 0 AND created_at <= (SELECT created_at FROM messages WHERE id = ?)",
			chatID, authID, lastMessageID).
		Update("views_count", 1)

	payload, _ := json.Marshal(map[string]string{
		"chatID":        chatID,
		"userID":        authID,
		"lastMessageID": lastMessageID,
	})
	r.redisClient.Publish(ctx, "read:"+chatID, payload)

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}
	return r.userRepo.GetByID(authID)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, userID string) ([]*models.Session, error) {
	authID := middleware.GetUserID(ctx)
	if authID != userID {
		return nil, errors.New("forbidden")
	}
	return r.userRepo.GetSessions(userID)
}

// MyChats is the resolver for the myChats field.
func (r *queryResolver) MyChats(ctx context.Context) ([]*model.Chat, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	resp, err := r.chatClient.GetMyChats(ctx, &chatpb.GetMyChatsRequest{UserId: authID})
	if err != nil {
		return nil, err
	}

	chats := make([]*model.Chat, 0, len(resp.Chats))
	for _, c := range resp.Chats {
		enriched, err := r.enrichChat(ctx, authID, c)
		if err != nil {
			continue
		}
		chats = append(chats, enriched)
	}

	return chats, nil
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id *string, slug *string) (*model.Chat, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return nil, errors.New("unauthorized")
	}

	resp, err := r.chatClient.GetChat(ctx, &chatpb.GetChatRequest{
		ChatId: id,
		Slug:   slug,
		UserId: authID,
	})
	if err != nil {
		return nil, err
	}

	return r.enrichChat(ctx, authID, resp.Chat)
}

// MessageHistory is the resolver for the messageHistory field.
func (r *queryResolver) MessageHistory(ctx context.Context, chatID string, limit int, offset int) ([]*models.Message, error) {
	resp, err := r.messagesClient.GetHistory(ctx, &messagespb.GetHistoryRequest{
		ChatId: chatID,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		return nil, err
	}
	var msgs []*models.Message
	for _, m := range resp.Messages {
		sentAt, _ := time.Parse(time.RFC3339, m.SentAt)
		msgs = append(msgs, &models.Message{
			ID:        m.Id,
			DialogID:  m.ChatId,
			AuthorID:  m.SenderId,
			Content:   m.Text,
			CreatedAt: sentAt,
		})
	}
	return msgs, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, username string) ([]*models.User, error) {
	if len(username) < 3 {
		return nil, errors.New("search query too short")
	}
	return r.userRepo.SearchByUsername(username)
}

// CreatedAt is the resolver for the createdAt field.
func (r *sessionResolver) CreatedAt(ctx context.Context, obj *models.Session) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, chatID string) (<-chan *models.Message, error) {
	msgChan := make(chan *models.Message, 1)
	pubsub := r.redisClient.Subscribe(ctx, "chat_updates:"+chatID)
	go func() {
		defer pubsub.Close()
		defer close(msgChan)
		ch := pubsub.Channel()
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-ch:
				if !ok {
					return
				}
				var m models.Message
				if err := json.Unmarshal([]byte(msg.Payload), &m); err == nil {
					msgChan <- &m
				}
			}
		}
	}()
	return msgChan, nil
}

// UserStatusChanged is the resolver for the userStatusChanged field.
func (r *subscriptionResolver) UserStatusChanged(ctx context.Context, chatID string) (<-chan *model.UserStatusPayload, error) {
	statusChan := make(chan *model.UserStatusPayload, 1)
	pubsub := r.redisClient.Subscribe(ctx, "presence:updates")

	go func() {
		defer pubsub.Close()
		defer close(statusChan)

		for {
			select {
			case <-ctx.Done():
				return
			case msg := <-pubsub.Channel():
				var p model.UserStatusPayload
				if json.Unmarshal([]byte(msg.Payload), &p) == nil {
					statusChan <- &p
				}
			}
		}
	}()

	return statusChan, nil
}

func (r *mutationResolver) TerminateSession(ctx context.Context, id string) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, errors.New("unauthorized")
	}

	var session models.Session
	if err := r.db.Where("id = ? AND user_id = ?", id, authID).First(&session).Error; err != nil {
		return false, errors.New("session not found")
	}

	if err := r.userRepo.TerminateSession(id); err != nil {
		return false, err
	}

	return true, nil
}

func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	authID := middleware.GetUserID(ctx)
	if authID == "" {
		return false, errors.New("unauthorized")
	}

	sessionID := middleware.GetSessionID(ctx)
	if sessionID == "" {
		return false, errors.New("session not found")
	}

	if err := r.userRepo.TerminateSession(sessionID); err != nil {
		return false, err
	}

	return true, nil
}

// MessageRead is the resolver for the messageRead field.
func (r *subscriptionResolver) MessageRead(ctx context.Context, chatID string) (<-chan *model.ReadPayload, error) {
	readChan := make(chan *model.ReadPayload, 1)
	pubsub := r.redisClient.Subscribe(ctx, "read:"+chatID)
	authID := middleware.GetUserID(ctx)
	go func() {
		defer pubsub.Close()
		defer close(readChan)
		for {
			select {
			case <-ctx.Done():
				return
			case msg := <-pubsub.Channel():
				var p model.ReadPayload
				if err := json.Unmarshal([]byte(msg.Payload), &p); err == nil {
					if p.UserID != authID {
						readChan <- &p
					}
				}
			}
		}
	}()
	return readChan, nil
}

// Status is the resolver for the status field.
func (r *userResolver) Status(ctx context.Context, obj *models.User) (string, error) {
	return r.presenceRepo.GetStatus(ctx, obj.ID)
}

// Message returns MessageResolver implementation.
func (r *Resolver) Message() MessageResolver { return &messageResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Session returns SessionResolver implementation.
func (r *Resolver) Session() SessionResolver { return &sessionResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type messageResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sessionResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
