/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as publicSignupRouteImport } from './app/routes/(public)/signup'
import { Route as publicOtpRouteImport } from './app/routes/(public)/otp'
import { Route as publicLoginRouteImport } from './app/routes/(public)/login'
import { Route as protectedLayoutRouteImport } from './app/routes/(protected)/_layout'
import { Route as protectedLayoutIndexRouteImport } from './app/routes/(protected)/_layout/index'
import { Route as protectedLayoutUserUserIdRouteImport } from './app/routes/(protected)/_layout/user.$userId'
import { Route as protectedLayoutChatChatIdRouteImport } from './app/routes/(protected)/_layout/chat.$chatId'

const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOtpRoute = publicOtpRouteImport.update({
  id: '/(public)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutUserUserIdRoute =
  protectedLayoutUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutChatChatIdRoute =
  protectedLayoutChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/otp': typeof publicOtpRoute
  '/signup': typeof publicSignupRoute
  '/': typeof protectedLayoutIndexRoute
  '/chat/$chatId': typeof protectedLayoutChatChatIdRoute
  '/user/$userId': typeof protectedLayoutUserUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/otp': typeof publicOtpRoute
  '/signup': typeof publicSignupRoute
  '/': typeof protectedLayoutIndexRoute
  '/chat/$chatId': typeof protectedLayoutChatChatIdRoute
  '/user/$userId': typeof protectedLayoutUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/otp': typeof publicOtpRoute
  '/(public)/signup': typeof publicSignupRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/chat/$chatId': typeof protectedLayoutChatChatIdRoute
  '/(protected)/_layout/user/$userId': typeof protectedLayoutUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/otp'
    | '/signup'
    | '/'
    | '/chat/$chatId'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/otp' | '/signup' | '/' | '/chat/$chatId' | '/user/$userId'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(public)/login'
    | '/(public)/otp'
    | '/(public)/signup'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/chat/$chatId'
    | '/(protected)/_layout/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicOtpRoute: typeof publicOtpRoute
  publicSignupRoute: typeof publicSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/otp': {
      id: '/(public)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof publicOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/user/$userId': {
      id: '/(protected)/_layout/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof protectedLayoutUserUserIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/chat/$chatId': {
      id: '/(protected)/_layout/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof protectedLayoutChatChatIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutChatChatIdRoute: typeof protectedLayoutChatChatIdRoute
  protectedLayoutUserUserIdRoute: typeof protectedLayoutUserUserIdRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutChatChatIdRoute: protectedLayoutChatChatIdRoute,
  protectedLayoutUserUserIdRoute: protectedLayoutUserUserIdRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicOtpRoute: publicOtpRoute,
  publicSignupRoute: publicSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
