/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as publicSignupRouteImport } from './app/routes/(public)/signup'
import { Route as publicOtpRouteImport } from './app/routes/(public)/otp'
import { Route as publicLoginRouteImport } from './app/routes/(public)/login'
import { Route as protectedLayoutRouteImport } from './app/routes/(protected)/_layout'
import { Route as protectedLayoutIndexRouteImport } from './app/routes/(protected)/_layout/index'
import { Route as protectedLayoutSettingsRouteImport } from './app/routes/(protected)/_layout/settings'
import { Route as protectedLayoutBotsIndexRouteImport } from './app/routes/(protected)/_layout/bots.index'
import { Route as protectedLayoutUserUserIdRouteImport } from './app/routes/(protected)/_layout/user.$userId'
import { Route as protectedLayoutChatChatIdRouteImport } from './app/routes/(protected)/_layout/chat.$chatId'
import { Route as protectedLayoutBotsCreateRouteImport } from './app/routes/(protected)/_layout/bots.create'
import { Route as protectedLayoutBotsBotIdRouteImport } from './app/routes/(protected)/_layout/bots.$botId'

const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOtpRoute = publicOtpRouteImport.update({
  id: '/(public)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutSettingsRoute = protectedLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutBotsIndexRoute =
  protectedLayoutBotsIndexRouteImport.update({
    id: '/bots/',
    path: '/bots/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutUserUserIdRoute =
  protectedLayoutUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutChatChatIdRoute =
  protectedLayoutChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutBotsCreateRoute =
  protectedLayoutBotsCreateRouteImport.update({
    id: '/bots/create',
    path: '/bots/create',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutBotsBotIdRoute =
  protectedLayoutBotsBotIdRouteImport.update({
    id: '/bots/$botId',
    path: '/bots/$botId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/otp': typeof publicOtpRoute
  '/signup': typeof publicSignupRoute
  '/settings': typeof protectedLayoutSettingsRoute
  '/': typeof protectedLayoutIndexRoute
  '/bots/$botId': typeof protectedLayoutBotsBotIdRoute
  '/bots/create': typeof protectedLayoutBotsCreateRoute
  '/chat/$chatId': typeof protectedLayoutChatChatIdRoute
  '/user/$userId': typeof protectedLayoutUserUserIdRoute
  '/bots/': typeof protectedLayoutBotsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/otp': typeof publicOtpRoute
  '/signup': typeof publicSignupRoute
  '/settings': typeof protectedLayoutSettingsRoute
  '/': typeof protectedLayoutIndexRoute
  '/bots/$botId': typeof protectedLayoutBotsBotIdRoute
  '/bots/create': typeof protectedLayoutBotsCreateRoute
  '/chat/$chatId': typeof protectedLayoutChatChatIdRoute
  '/user/$userId': typeof protectedLayoutUserUserIdRoute
  '/bots': typeof protectedLayoutBotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/otp': typeof publicOtpRoute
  '/(public)/signup': typeof publicSignupRoute
  '/(protected)/_layout/settings': typeof protectedLayoutSettingsRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/bots/$botId': typeof protectedLayoutBotsBotIdRoute
  '/(protected)/_layout/bots/create': typeof protectedLayoutBotsCreateRoute
  '/(protected)/_layout/chat/$chatId': typeof protectedLayoutChatChatIdRoute
  '/(protected)/_layout/user/$userId': typeof protectedLayoutUserUserIdRoute
  '/(protected)/_layout/bots/': typeof protectedLayoutBotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/otp'
    | '/signup'
    | '/settings'
    | '/'
    | '/bots/$botId'
    | '/bots/create'
    | '/chat/$chatId'
    | '/user/$userId'
    | '/bots/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/otp'
    | '/signup'
    | '/settings'
    | '/'
    | '/bots/$botId'
    | '/bots/create'
    | '/chat/$chatId'
    | '/user/$userId'
    | '/bots'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(public)/login'
    | '/(public)/otp'
    | '/(public)/signup'
    | '/(protected)/_layout/settings'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/bots/$botId'
    | '/(protected)/_layout/bots/create'
    | '/(protected)/_layout/chat/$chatId'
    | '/(protected)/_layout/user/$userId'
    | '/(protected)/_layout/bots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicOtpRoute: typeof publicOtpRoute
  publicSignupRoute: typeof publicSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/otp': {
      id: '/(public)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof publicOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/settings': {
      id: '/(protected)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedLayoutSettingsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/bots/': {
      id: '/(protected)/_layout/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof protectedLayoutBotsIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/user/$userId': {
      id: '/(protected)/_layout/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof protectedLayoutUserUserIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/chat/$chatId': {
      id: '/(protected)/_layout/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof protectedLayoutChatChatIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/bots/create': {
      id: '/(protected)/_layout/bots/create'
      path: '/bots/create'
      fullPath: '/bots/create'
      preLoaderRoute: typeof protectedLayoutBotsCreateRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/bots/$botId': {
      id: '/(protected)/_layout/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof protectedLayoutBotsBotIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutSettingsRoute: typeof protectedLayoutSettingsRoute
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutBotsBotIdRoute: typeof protectedLayoutBotsBotIdRoute
  protectedLayoutBotsCreateRoute: typeof protectedLayoutBotsCreateRoute
  protectedLayoutChatChatIdRoute: typeof protectedLayoutChatChatIdRoute
  protectedLayoutUserUserIdRoute: typeof protectedLayoutUserUserIdRoute
  protectedLayoutBotsIndexRoute: typeof protectedLayoutBotsIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutSettingsRoute: protectedLayoutSettingsRoute,
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutBotsBotIdRoute: protectedLayoutBotsBotIdRoute,
  protectedLayoutBotsCreateRoute: protectedLayoutBotsCreateRoute,
  protectedLayoutChatChatIdRoute: protectedLayoutChatChatIdRoute,
  protectedLayoutUserUserIdRoute: protectedLayoutUserUserIdRoute,
  protectedLayoutBotsIndexRoute: protectedLayoutBotsIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicOtpRoute: publicOtpRoute,
  publicSignupRoute: publicSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
