// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	Expiry    time.Time `json:"expiry"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	IpAddress string    `json:"ip_address"`
	Device    string    `json:"device"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                 uuid.UUID      `json:"id"`
	Username           sql.NullString `json:"username"`
	FirstName          string         `json:"first_name"`
	LastName           sql.NullString `json:"last_name"`
	Email              string         `json:"email"`
	Password           string         `json:"password"`
	Status             string         `json:"status"`
	IsPremium          bool           `json:"is_premium"`
	IsEmailVerified    bool           `json:"is_email_verified"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationExpiry sql.NullTime   `json:"verification_expiry"`
	PublicKey          sql.NullString `json:"public_key"`
	EncryptedPrivKey   sql.NullString `json:"encrypted_priv_key"`
	EncryptionIv       sql.NullString `json:"encryption_iv"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}
