// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CheckUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error)
	SearchUsersByUsername(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersGlobal(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
